### ISSUE TITLE
Fix default weapon model in Player Setup screen

### ISSUE THREAD

**Issue by darkshade9** [actionquake/distrib#12]
Weapon model in Player Setup screen is the Quake II railgun.  We should change this to be something else, like the M4 or Shotgun
![quake000](https://user-images.githubusercontent.com/1392336/163038115-bbde1fc0-0646-4f04-8752-d5baa1372245.jpg)
?

**Comment by vrolse** [comment]
In q2pro.menu in the top where you have "weapon <model>" change that to "weapon w_sniper.md2" I think this should work. Maybe this model can't be in a *.pkz file?

**Comment by darkshade9** [comment]
I think this PR fixed this issue https://github.com/actionquake/distrib/pull/18
