### ISSUE TITLE
Missing texture: players/terror/akimbo.pcx

### ISSUE THREAD

**Issue by Raptor007** [actionquake/distrib#132]
Inside 0_default-game-content.pkz, players/terror/w_akimbo.md2 looks for the texture players/terror/akimbo.pcx, but that file is missing.

Here's the missing texture file: [terror_akimbo.zip](https://github.com/actionquake/distrib/files/8819270/terror_akimbo.zip)

**Comment by darkshade9** [comment]
Thanks, we'll get this added for the next release!
