### ISSUE TITLE
Clean Mac upgrade path

### ISSUE THREAD

**Issue by darkshade9** [actionquake/distrib#16]
Currently, Mac installs are done with the simple 'drag this App to the Applications symlink'.  If the player changed any configs, binds, anything at all, this process wipes all of that out and starts fresh.  What we want is for the 'base game' to be the drag-n-drop install, and that the user-provided pkz files and config changes to persist on every upgrade.  Figure out a solution for both Intel and M1 Mac that we can incorporate in the install/upgrade process.

@ndit-dev I think you did some work on this?

**Comment by ndit-dev** [comment]
Yes, I have fixed that in the m1 executable and make file already by compiling q2pro with CONFIG_PATH_HOME=~/actionquake. I'll push the same updated to intel-makefile also.

What it does basically is, use configs/pakfile/and other resources that are present in the .app-file. But if it's also present in ~/actionquake it will take precedence. In this way we can provide some nice defaults in the app-file, but instruct the end-user to place his or her files in ~/actionquake

**Comment by ndit-dev** [comment]
Just realized I had already pushed this to the intel makefile, so this change will take effect during your next build.

Don't have an Intel mac to test this, but should be fine

**Comment by darkshade9** [comment]
I tested the Intel build, seems to work great.  Downloaded content from the downloadserver and changes to binds/config goes to `~/aqtion`, so the current install process looks like it'll work great.
