### ISSUE TITLE
M4 sound too weak?

### ISSUE THREAD

**Issue by Raptor007** [actionquake/distrib#217]
This is just my subjective opinion.  I know AQtion has some assets replaced deliberately (the pistol sounds great!) but I think the M4 sounds too weak and similar to the MP5.  I'd prefer it to sound more like the original AQ2 M4: [m4a1fire.zip](https://github.com/actionquake/distrib/files/9332888/m4a1fire.zip)

**Comment by darkshade9** [comment]
We have some sound packs for the original sounds and alternative sounds if users want to use them.  We could host a poll for which default sounds we should use and update accordingly

Sound packs: https://forums.aq2world.com/viewforum.php?f=9

**Comment by Raptor007** [comment]
Interesting... many of the sounds in your "original-weapon-sounds.pkz" actually seem to be from [the Rogue Spear sound pak I'd made ages ago.](http://www.raptor007.com/rare-file-archive/aq2roguespear_v110.zip)  That explains the beefy pistol and weak M4, but I'm a little confused how those came to be known as "original".  Maybe my server has these wavs and has been giving them to new clients?  I should check on that.

Here are [the original AQ2 pak files](https://github.com/actionquake/distrib/files/9355406/aq2-paks.zip) and 
[a zip of just the sounds](https://github.com/actionquake/distrib/files/9355415/aq2-original-sounds.zip) which you can rename to pkz for AQtion.

**Comment by darkshade9** [comment]
I'll update the forums to make a distinction between the Rogue Spear sound pack and the _original_ original sounds

**Comment by Raptor007** [comment]
Awesome, thanks!  And I still think Rogue Spear is probably not the best default M4 sound, but again that's just my subjective opinion.

**Comment by darkshade9** [comment]
Related https://github.com/Raptor007/aq2-tng/issues/137

**Comment by darkshade9** [comment]
Newest release (v1.3) has updated M4 and MK23 firing sound effects

**Comment by darkshade9** [comment]
Marking as resolved as AQtion v1.3 has support for multiple gun sounds via `llsound 1` and checking out your menu Sound settings, or reviewing the llsound documentation in AQ2-TNG -- https://github.com/actionquake/aq2-tng/blob/aqtion/TNG-manual.txt#L164-L198
