### ISSUE TITLE
Make it clear that distributed Q2PRO binary is a fork

### ISSUE THREAD

**Issue by skullernet** [actionquake/distrib#276]
I'd appreciate if users are clearly notified that Q2PRO binary distributed in this package (and Steam) is not an upstream version, but a fork. It's OK to say the game engine is based on Q2PRO, but it should not be confused with upstream project.

`PRODUCT` is already defined to `AQtion` in source code, which is good. I'd like to also request that at least:
* Link to upstream Q2PRO github page is removed from console.
* Windows resource files are modified to not include link to Q2PRO github page, and all instances of `Q2PRO` and `skuller.net` are removed.

Thanks!

**Comment by darkshade9** [comment]
Thanks for reaching out @skullernet -- this is no problem, I can have this done by next release.  I wanted to ensure that credit is given where credit is due; I deferred to making it more than clear that I am not the primary maintainer of the upstream project.

We appreciate all the hard work you've dedicated to Q2Pro!

**Comment by darkshade9** [comment]
Closing as completed
