### ISSUE TITLE
Leftover Q2 assets

### ISSUE THREAD

**Issue by res2k** [actionquake/distrib#290]
Hi, I noticed the following assets, which look suspiciously like their counterparts Q2:
baseaq/pak0/models/items/healing/medium/skin.pcx
baseaq/pak0/models/objects/explode/
baseaq/pak0/models/objects/flash/
baseaq/pak0/models/objects/minelite/light1/base.pcx
baseaq/pak0/models/objects/minelite/light2/base.pcx

**Comment by darkshade9** [comment]
Yep, good looking out here, thanks.  The pcx files must have been forgotten about because the HD textures are what most if not all players use (the png/tng file).  These will be removed ASAP.

**Comment by darkshade9** [comment]
https://github.com/actionquake/distrib/releases/tag/v1.3.5
