### ISSUE TITLE
Game crashing when playing online

### ISSUE THREAD

**Issue by SoundFactor** [actionquake/distrib#301]
I can only play locally with bots, cannot play any other way without it straight crashing.

Attached crash report. Crash report includes full system specs.

[crash report.docx](https://github.com/actionquake/distrib/files/11550019/crash.report.docx)

**Comment by darkshade9** [comment]
It looks like this is the culprit?

```
Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: _curl_multi_poll
  Referenced from: /Users/USER/Library/Application Support/Steam/*/q2pro
  Expected in: /usr/lib/libcurl.4.dylib
```

What version of libcurl do you have?  Can you try to reinstall via `brew install curl` ?

**Comment by SoundFactor** [comment]
It installed something but that didn't fix the problem :(

**Comment by darkshade9** [comment]
@SoundFactor I noticed there was an update on this steam guide, was this from you?
https://steamcommunity.com/sharedfiles/filedetails/?id=2817966054
Are you still having problems or are you good to go?

**Comment by SoundFactor** [comment]
I had to run a OS system update which fixed all my issues.
