### ISSUE TITLE
jump: spawns

### ISSUE THREAD

**Issue by MVarland** [actionquake/distrib#302]
More than 50% map votes reached.
Game ending at: Sunday 03 September 14:44:00
Next map was voted on and is aries.
------- Server Initialization -------
SpawnServer: aries
action/sndlist.ini is empty, no sounds to precache.
11 tourney events...
0 entities inhibited
0 teams with 0 entities
No location file for aries
ACE: No node file found, creating new one...done.
-------------------------------------
Warning: failed to find deathmatch spawn point
********************
ERROR: Game Error: Couldn't find spawn point

********************
Q2A Lua: Shutdown in progress...
Q2A Lua: unloading plugins/broadcast.lua
Q2A Lua: unloading plugins/coinflip.lua
Q2A Lua: unloading plugins/scoreboardStore.lua
Q2A Lua: unloading plugins/mvd.lua
Q2A Lua: unloading plugins/mvd2cprints.lua
Q2A Lua: unloading plugins/version.lua
Q2A Lua: All plugins unloaded!
==== ShutdownGame ====

**Comment by darkshade9** [comment]
Almost certainly to do with lack of `info_player_deathmatch` -- we should create a bug issue in https://github.com/actionquake/aq2-tng/issues to address this.  It specifically affects `jump` mode

**Comment by darkshade9** [comment]
To verify @MVarland try one of these maps with 3 spawnpoints, and others with 2 spawnpoints.  If 2 doesn't work and 3 does, then I think I know what our minimum requirement is:

```
aboveclouds.bsp: 3
aq2ctf1.bsp: 0
aq2ctf3.bsp: 0
aq2ctf_spacedome.bsp: 0
aq2snipe.bsp: 2
aq2soccer.bsp: 0
arabtown.bsp: 2
arabtown2.bsp: 3
aries.bsp: 2
armyterr.bsp: 2
artmuseum.bsp: 3
beneath1.bsp: 3
cancliff.bsp: 2
cjpiy.bsp: 3
closec.bsp: 2
cloud.bsp: 3
cloudx.bsp: 2
crassi.bsp: 1
credits.bsp: 1
ctfdesert.bsp: 0
ctfjump.bsp: 0
ctfwargrounds.bsp: 0
cucu40a.bsp: 3
deatharena.bsp: 2
desertbattle.bsp: 0
dirt-aq2.bsp: 2
dirt.bsp: 2
ea.bsp: 2
enkelt.bsp: 3
escapizm.bsp: 1
facingworlds.bsp: 0
ff.bsp: 3
ff2.bsp: 2
flooded2.bsp: 2
flyjumpboy.bsp: 0
futis.bsp: 0
giza.bsp: 3
gravee2.bsp: 1
groove.bsp: 3
hermi.bsp: 3
hopp.bsp: 2
hopp2.bsp: 2
icetoxin.bsp: 2
jac.bsp: 2
jepjepu1.bsp: 0
kcity.bsp: 2
kcityp.bsp: 2
kicks.bsp: 2
kicksv2.bsp: 2
marina.bsp: 0
mixmuseum.bsp: 3
mixmuseum2.bsp: 3
newcloud.bsp: 3
newff.bsp: 3
oilrig.bsp: 3
pgjumps2.bsp: 0
pilvessa.bsp: 3
pmetsa.bsp: 2
putkine1.bsp: 1
putkine2.bsp: 1
putkine3.bsp: 1
reformer2000.bsp: 2
retro.bsp: 1
riverwar.bsp: 2
rooms.bsp: 1
serebryanka.bsp: 3
shroud.bsp: 2
skeet3.bsp: 2
skiejmp1.bsp: 3
sludge.bsp: 0
summerplace.bsp: 1
sunken3.bsp: 2
tainted.bsp: 3
teamjungle_golf.bsp: 2
theist.bsp: 2
time.bsp: 3
tterminal.bsp: 2
tterminalp.bsp: 2
twoface.bsp: 0
volcano1.bsp: 1
voracity.bsp: 0
warehouse.bsp: 2
wolk.bsp: 2
wrestle.bsp: 2
zcity.bsp: 2
```

**Comment by MVarland** [comment]
aries (2) crashes the server
closec (2) crashes the server


aboveclouds (3) works
cloudx (2) works
credits (1) works
futis (0) works

Sort of on this topic: I think we should change jump mode to only use teamplay spawns (or have it chooseable somehow. Like jmod spawns tp / jmod spawns dm / jmod spawns ctf ?

**Comment by darkshade9** [comment]
After playing with how spawning works in general (Espionage specifically) I've come to understand the system a bit better.  It tries several different combinations right now to find a spawnpoint, and if one can't be found then the server crashes.  This should never happen normally of course.  I will take a look at making these maps usable in jmod.

As an aside, CTF mode does a good job of trying _everything_ it can to find a flag spawn, even so far as to converting existing entity classes to flag spawn points so that CTF is possible, but it may not be balanced.

**Comment by darkshade9** [comment]
Can you confirm the latest versions are no longer crashing?  I've lost track of when I made these changes and whether they're in the latest client distrib or just the servers @MVarland

**Comment by MVarland** [comment]
Latest client distrib working
server:latest working
server:v46-jmod1 working
