### ISSUE TITLE
Quick Join feature

### ISSUE THREAD

**Issue by darkshade9** [actionquake/distrib#46]
Work with other server admins to create a 'ring' of `sv_redirect_address` where a player utilizing the Quick Join feature will attempt to join a server, and if that server is full, it will automatically redirect the player to this address.  If that server is also full, it continues to redirect until a server slot is found for the player.

Example:

By default, the **Quickjoin** menu item issues the command `connect useast.aq2world.com:27910`, so all players who use this command will connect to that server first.  If that server is full, it has a server cvar *sv_redirect_address* of `aq2.vrol.se:27910`, so that player would connect to vrol's server.  If *that* server is full, vrol's config should have an *sv_redirect_address* going to somewhere else.  And so on, like a ring.

Requirements:
Everyone who wants to participate in this 'webring' of AQtion servers needs to use a standard set of configurations such that player experience does not deviate much.

**Comment by darkshade9** [comment]
Alternatively, we could find a way to use a free/cheap global load balancer that will send players to servers that are more acceptable as far as latency.

**Comment by ndit-dev** [comment]
A middle ground could be...

set up a few dns-records like
useast.quickjoin.aq2world.com
uswest.quickjoin.aq2world.com
eu.quickjoin.aq2world.com
aus.quickjoin.aq2world.com

so the "first server" can be change without changeing updating the game. Then do the reconnect ring as you suggest.

**Comment by darkshade9** [comment]
Hmm, what if the QuickJoin feature had options like:

Main Menu
  Play Online
    QuickJoin
      US East
        `connect useast.quickjoin.aqtiongame.com:27910` -> this follows the US East Server Ring, spillover into US West
      US West
        `connect uswest.quickjoin.aqtiongame.com:27910` -> this follows the US West Server Ring, spillover into US East
      EU North
        `connect eunorth.quickjoin.aqtiongame.com:27910` -> this follows the EU North Server Ring, spillover into EU Central
      EU West
        `connect euwest.quickjoin.aqtiongame.com:27910` -> this follows the EU West Server Ring, spillover into EU North
      EU Central
        `connect eucentral.quickjoin.aqtiongame.com:27910` -> this follows the EU Central Server Ring, spillover into EU West
      AU East
        `connect aueast.quickjoin.aqtiongame.com:27910` -> this follows the AU East Server Ring, spillover into AU West
      AU West
        `connect auwest.quickjoin.aqtiongame.com:27910` -> this follows the AU West Server Ring, spillover into AU East
      BR?  CL?
