### ISSUE TITLE
Investigate steamshim for Achievements and Stats

### ISSUE THREAD

**Issue by darkshade9** [actionquake/distrib#47]
https://github.com/icculus/steamshim

**Comment by Raptor007** [comment]
To get the stats from the game, I think you'll need to look for them in q2pro/src/client.c CL_ParsePrint:
https://github.com/actionquake/q2pro/blob/e8020e9c9fad18bee7e6b26e5ac1b45d94674375/src/client/parse.c#L937-L940

Something like this, though my SteamShim code may not be quite right:
```
    if (level != PRINT_CHAT) {
        Com_Printf("%s", s);
        if (!cls.demo.playback && cl.serverstate != ss_broadcast) {
            COM_strclr(s);
            Cmd_ExecTrigger(s);
            AqtionParseMessage(s);
        }
        return;
    }
```
```
void AqtionParseMessage( const char *s )
{
	if( ! strncmp( s, "You hit ", 8 ) && strstr( s, " in the head\n" ) )
		AqtionHeadshot();
}

void AqtionHeadshot( void )
{
	int headshots = AqtionIncrementStat( "Headshots" );
	if( headshots >= 100 )
	{
		STEAMSHIM_setAchievement( "HEADSHOTS_100", 1 );
		STEAMSHIM_storeStats();
	}
}

int AqtionIncrementStat( const char *stat )
{
	int count = 0;
	const STEAMSHIM_Event *e = NULL;
	time_t giveup = time(NULL) + 2;
	STEAMSHIM_requestStats();
	STEAMSHIM_getStatI( stat );
	while( STEAMSHIM_alive() && (time(NULL) < giveup) && ((e = STEAMSHIM_pump())) )
	{
		if( (e.type == SHIMEVENT_GETSTATI) && ! strcmp( e.name, stat ) )
			count = e.ivalue;
	}
	count ++;
	STEAMSHIM_setStatI( stat, count );
	STEAMSHIM_storeStats();
	while( STEAMSHIM_alive() && (time(NULL) < giveup) && ((e = STEAMSHIM_pump())) );
	return count;
}
```

**Comment by darkshade9** [comment]
Assuming that it works out of the box like that, would we have a giant list of if else or case switch for each type of event?  Chest kills, kicks, knife slashes, fall deaths, every event that has a printable event?

**Comment by Raptor007** [comment]
Yes I think so, but you only need to handle the events that matter for achievements.

Fortunately all headshots print "You hit X in the head\n" so that one is easy.  I'd start with that one to get the achievement system working.

Tracking kills would require matching several different strings based on weapon and damage location, and you'll need to make sure the client's name is in the part of the string that credits the kill.  The good news is once you've implemented all those string matches, you can use them to track kills by damage location, kills by weapon type, etc.

**Comment by darkshade9** [comment]
The users' steamid is registered when the shim is launched, so we have an immutable unique ID for each player to key off of.  Could we potentially also get a viewpos of killer/victim for heatmaps upon events?

**Comment by darkshade9** [comment]
I managed to get the steamshim to work for Mac and Linux, and it passes the user's Steam id as a `CVAR_NOSET` and `CVAR_USERINFO`, and added it to the userinfo string.

<img width="582" alt="image" src="https://user-images.githubusercontent.com/1392336/174458964-bccfce13-1a9a-471a-98f6-510bcf037548.png">

**Comment by darkshade9** [comment]
Closing this issue.  For those keeping score at home, this is a big hint on what's coming soon
